version: '3.8'

services:
  # 主 API 服务
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    environment:
      - YOUTUBE_DEBUG=false
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always

networks:
  default:
    driver: bridge 