version: '3.8'

services:
  # bgutil PO Token provider 服务
  bgutil-provider:
    image: brainicism/bgutil-ytdlp-pot-provider:latest
    container_name: bgutil-provider
    ports:
      - "4416:4416"
    environment:
      - TOKEN_TTL=6  # PO Token 缓存时间（小时）
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4416/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 主 API 服务
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - /var/run/docker.sock:/var/run/docker.sock  # 允许访问 Docker daemon
    depends_on:
      bgutil-provider:
        condition: service_healthy
    environment:
      - BGUTIL_PROVIDER_URL=http://bgutil-provider:4416
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always

networks:
  default:
    driver: bridge 